sudo: false
language: node_js
notifications:
  email: false
node_js:
  - '8'
install: npm install
before_script:
  - npm prune
script:
  - npm run build
after_success:
  - npm run release
branches:
  only:
    - master
